direction: down

**.style.border-radius: 8

pre_training: "Pre Training" {
  style: {
    stroke-dash: 2
  }
  data: "Data" {
    shape: stored_data
  }
  neural_network: "Neural Network" {
    style.fill: "#1B1A55"
  }
  pretrained_model: "Foundation Model" {
    style.fill: "#BE3144"
    shape: rectangle
  }
}

pre_training.data -> pre_training.neural_network: {
  style: {
    animated: true
  }
}
pre_training.neural_network -> pre_training.pretrained_model

instruction_tuning: "Instruction Tuning" {
  style: {
    stroke-dash: 2
  }
  instruction_data: "Instruction Data" {
    shape: stored_data
  }
  instruction_tuned_model: "Instruction Following Model" {
    shape: rectangle
    style.fill: "#4e2eff"
  }
}
pre_training.pretrained_model -> instruction_tuning.instruction_tuned_model
instruction_tuning.instruction_data -> instruction_tuning.instruction_tuned_model: {
  style: {
    animated: true
  }
}

fine_tuning: "Fine Tuning" {
  style: {
    stroke-dash: 2
  }
  domain_specific_data: "Domain Specific Data" {
    shape: stored_data
  }
  fine_tuned_model: "Fine Tuned Model" {
    shape: rectangle
    style.fill: "teal"
  }
}
instruction_tuning.instruction_tuned_model -> fine_tuning.fine_tuned_model
fine_tuning.domain_specific_data -> fine_tuning.fine_tuned_model: {
  style: {
    animated: true
  }
}

pre_training -> instruction_tuning -> fine_tuning
